<?php

/**
 * @file
 * Functions to support theming.
 */

/**
 * Implements hook_preprocess_image_widget().
 */

function armazens_preprocess(array &$variables) {
$variables['is_front'] = \Drupal::service('path.matcher')->isFrontPage();
}

function armazens_preprocess_image_widget(array &$variables) {
  $data = &$variables['data'];

  // This prevents image widget templates from rendering preview container HTML
  // to users that do not have permission to access these previews.
  // @todo revisit in https://drupal.org/node/953034
  // @todo revisit in https://drupal.org/node/3114318
  if (isset($data['preview']['#access']) && $data['preview']['#access'] === FALSE) {
    unset($data['preview']);
  }
}

function armazens_form_alter(&$form, \Drupal\Core\Form\FormStateInterface $form_state, $form_id) {
  $form['revision_information']['#access'] = FALSE;
  $form['actions']['preview']['#access'] = FALSE;

  $form['field_documentos']['widget']['#type'] = 'fieldset';
  
  if($form_id == 'node_armazem_form') {
    $form['field_fotos']['widget']['#type'] = 'fieldset';
  }

  if($form_id == 'node_armazem_step_4_form') {
    $form_state->getBuildInfo()['callback_object']->getEntity()->setPublished(TRUE);
  }
}